# Generated by Django 2.2.16 on 2021-01-13 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='難易度')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='レシピタイトル')),
                ('calorie', models.CharField(default='', max_length=4, verbose_name='カロリー')),
                ('time', models.CharField(default='', max_length=3, verbose_name='調理時間')),
                ('process', models.CharField(default='', max_length=2, verbose_name='調理工程数')),
                ('motion', models.CharField(default='', max_length=2, verbose_name='調理動作数')),
                ('ingredients', models.CharField(default='', max_length=2, verbose_name='食材数')),
                ('material', models.TextField(default='', verbose_name='材料')),
                ('text', models.TextField(verbose_name='作り方')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='栄養素')),
                ('link', models.URLField(blank=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.Category', verbose_name='カテゴリー')),
            ],
            options={
                'verbose_name': 'レシピ',
                'verbose_name_plural': 'レシピ',
            },
        ),
    ]
