# Generated by Django 2.2.16 on 2020-12-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201230_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='time',
            field=models.CharField(default='', max_length=3, verbose_name='調理時間'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='栄養素'),
        ),
        migrations.AlterField(
            model_name='post',
            name='material',
            field=models.TextField(default='', verbose_name='材料'),
        ),
    ]
