# Generated by Django 2.2.16 on 2020-12-29 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201230_0355'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='process',
            field=models.CharField(default='', max_length=2, verbose_name='調理工程数'),
        ),
    ]
