# Generated by Django 2.2.16 on 2020-12-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='motion',
            field=models.CharField(default='', max_length=2, verbose_name='調理動作数'),
        ),
    ]
