# Generated by Django 2.2.16 on 2021-01-14 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210114_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='carbohydrate',
            field=models.CharField(default='', max_length=3, verbose_name='炭水化物'),
        ),
        migrations.AddField(
            model_name='post',
            name='lipid',
            field=models.CharField(default='', max_length=3, verbose_name='脂質'),
        ),
        migrations.AddField(
            model_name='post',
            name='protein',
            field=models.CharField(default='', max_length=3, verbose_name='たんぱく質'),
        ),
    ]
