# Generated by Django 2.2.16 on 2021-01-14 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210114_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='栄養素4'),
        ),
    ]
