# Generated by Django 2.2.16 on 2021-01-14 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20210114_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.TextField(default='', verbose_name='URL'),
        ),
    ]
