# Generated by Django 2.2.16 on 2021-01-14 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20210114_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.CharField(max_length=30, verbose_name='URL'),
        ),
    ]
