# Generated by Django 2.2.16 on 2021-01-17 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20210114_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='carbohydrate',
            field=models.FloatField(default='', max_length=3, verbose_name='炭水化物'),
        ),
    ]
