# Generated by Django 2.2.16 on 2021-01-17 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20210118_0437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='lipid',
            field=models.FloatField(default='', max_length=3, verbose_name='脂質'),
        ),
        migrations.AlterField(
            model_name='post',
            name='protein',
            field=models.FloatField(default='', max_length=3, verbose_name='たんぱく質'),
        ),
    ]
